inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

# 人の手で変更しないことが前提のファイルは除外
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

# ********************
# RailsのCops詳細設定
# ********************
# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 日本語コメントを許可する
Style/AsciiComments:
  Enabled: false

# and/orを使わない (&& / ||を使用)
Style/AndOr:
  Enabled: false

# 非推奨のOpenSSL定数の使用をチェック
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# DBディレクトリのファイルはABCサイズをチェックしない
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'db/**/*'

# DBディレクトリのファイルはメソッドの長さをチェックしない
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/**/*'

# 行の長さを100文字までに制限
Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/*'
    - 'Gemfile'
    - 'config/**/*'

# インデントの一貫性を強制
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# 文末のカンマを許可
Style/TrailingCommaInArguments:
  Exclude:
    - 'db/fixtures/*'

# ファイルの先頭に文字列をfreezeするかの記述を強制するチェックを無効化
Style/FrozenStringLiteralComment:
  Enabled: false

# ブロック行数の制限を無効化
Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/**/*'
    - 'config/**/*'
