FROM ruby:3.3.4-alpine

# 言語とタイムゾーンの設定
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo

WORKDIR /app

RUN apk update && \
    apk add --no-cache\
    alpine-sdk \
    build-base \
    sqlite-dev \
    postgresql-dev \
    tzdata \
    git \
    bash \
    gcompat

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN gem install bundler
RUN bundle install

COPY . /app/

# コンテナ起動時に実行するスクリプト
COPY ./entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0", "-e", "development"]
